spring:
  security:
    oauth2:
      client:
        registration:
          cognito:
            client-id: ${COGNITO_CLIENT_ID}
            client-secret: ${COGNITO_CLIENT_SECRET}
            scope: openid, email, profile
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            provider: cognito
        provider:
          cognito:
            # Replace {region} and {poolId} with your specific AWS Cognito values
            issuer-uri: ${COGNITO_ISSUER_URI}
            # user-name-attribute: username # Default is 'sub' which is safer

server:
  port: 8080
